TestGuru lesson_1
NicholasKrupenin/TestGuru pull request #1
Opened 2022-08-09 03:35 UTC by NicholasKrupenin

####  Good day

* first pull  request

2022-08-09 06:19 UTC, VidgarVii requested changes

2022-08-09 06:19 UTC, VidgarVii commented on README.md
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2022-08-09 06:19 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.available_locales = [:en, :ru]
в ТЗ сказано установить локаль по умолчанию, а не доступную

2022-08-09 06:19 UTC, VidgarVii commented on public/about.html
> +  <a href="http://www.thinknetica.com">
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-08-10 13:10 UTC, NicholasKrupenin commented on README.md
Исправил

2022-08-10 13:11 UTC, NicholasKrupenin commented on config/application.rb
> +    config.i18n.available_locales = [:en, :ru]
Дополнил

2022-08-10 13:11 UTC, NicholasKrupenin commented on public/about.html
> +  <a href="http://www.thinknetica.com">
Дополнил

2022-08-11 10:04 UTC, merged