Lesson 8
NicholasKrupenin/TestGuru pull request #11
Opened 2023-04-11 15:04 UTC by NicholasKrupenin

Привет

2023-04-12 04:04 UTC, VidgarVii requested changes

2023-04-12 04:04 UTC, VidgarVii commented on app/assets/stylesheets/application.css
> +}
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-04-12 04:04 UTC, VidgarVii commented on app/helpers/answers_helper.rb
> +      "Edit answer to a question: #{answer.question.body[0,20]}..."
https://apidock.com/rails/ActionView/Helpers/TextHelper/truncate

2023-04-12 04:04 UTC, VidgarVii commented on app/models/test_passage.rb
> +  before_update :before_update_set_next_question
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса

(и обрати внимание - оба вызываются с дополнительным условием, на создании или на апдейте)

имеет смысл объединить их в один простой коллбек:

```ruby
before_validation :set_current_question

...

def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

(коллбеки бывает удобно использовать, но они часто усложняют код и его отладку, если есть возможность не плодить лишние, то ей надо воспользоваться)


вообще с коллбеками нужно осторожно - они не всегда делают то что ты ожидаешь, тогда когда ты ожидаешь ))
бывают ньюансы о которых не догадываешься, особенно при совместной работе нескольких коллбеков и использовании коллбеков с условиями
поэтому если есть возможность упростить коллбеки, то это нужно делать

2023-04-12 04:04 UTC, VidgarVii commented on app/models/test_passage.rb
> +  end
нужно учесть, что пользователь может не выбрать ни одного ответа из предложенных и код от этого не должен падать

2023-04-12 04:04 UTC, VidgarVii commented on app/views/answers/_answer.html.erb
> +    <td><%= link_to 'Delete', answer_path(answer), method: :delete,
точно работает?

2023-04-12 10:47 UTC, NicholasKrupenin commented on app/assets/stylesheets/application.css
> +}
+

2023-04-12 11:17 UTC, NicholasKrupenin commented on app/helpers/answers_helper.rb
> +      "Edit answer to a question: #{answer.question.body[0,20]}..."
+

2023-04-12 12:44 UTC, NicholasKrupenin commented on app/views/answers/_answer.html.erb
> +    <td><%= link_to 'Delete', answer_path(answer), method: :delete,
+

2023-04-12 12:44 UTC, NicholasKrupenin commented on app/models/test_passage.rb
> +  before_update :before_update_set_next_question
+

2023-04-12 14:39 UTC, VidgarVii requested changes

2023-04-12 14:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +  end
получился код с запашком.
answer_ids.present? && correct_answers.ids ....
уже будет работать и смотрится лучше
но можно и без проверок
```
correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
```

2023-04-12 14:39 UTC, VidgarVii commented on app/views/test_passages/result.html.erb
> +<% if @test_passage.success_rate >= 85 %>
и лучше "магические цифры" хранить в константах с "говорящими именами"
например `SUCCESS_RATIO`

2023-04-12 16:30 UTC, NicholasKrupenin commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_current_question, on: [ :create, :update ]
+

2023-04-13 04:10 UTC, VidgarVii requested changes

2023-04-13 04:10 UTC, VidgarVii commented on app/models/test_passage.rb
> +    end
1 условный оператор тут лишний
2 первое вырожение проверки answer_ids лишние.
Разберись в коде

2023-04-13 15:18 UTC, merged