Lesson 10
NicholasKrupenin/TestGuru pull request #13
Opened 2023-04-25 22:52 UTC by NicholasKrupenin

Привет 0/

2023-04-26 03:53 UTC, VidgarVii requested changes

2023-04-26 03:53 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2023-04-26 03:53 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    byebug
отладочный код не должен попадать в репозиторий

2023-04-26 03:53 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
ТЗ
. При создании нового теста администратором назначайте его в качестве автора теста

2023-04-26 03:53 UTC, VidgarVii commented on app/helpers/application_helper.rb
> -  def flash_message(type)
в ТЗ не было сказано удаление этого метода.

2023-04-26 03:53 UTC, VidgarVii commented on app/views/devise/sessions/new.html.erb
> +<h2>Log in</h2>
все эти файлы от девайс можно не класть в репозиторий и стоит их удалить, если не собираешься их изменять

2023-04-26 03:53 UTC, VidgarVii commented on db/migrate/20230423222234_add_attribute_name_to_users.rb
> +  def change
1 эта миграция лишняя. Файл выше уже исправляет таблицу юзеров.
2 Рубокоп бы тут сильно ругался. 3 вызыва add_column можно заменить на
change_table :users

2023-04-26 08:40 UTC, NicholasKrupenin commented on app/controllers/admin/tests_controller.rb
> +  def start
+

2023-04-26 08:40 UTC, NicholasKrupenin commented on app/controllers/admin/tests_controller.rb
> +    byebug
+

2023-04-26 08:50 UTC, NicholasKrupenin commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
+

2023-04-26 08:54 UTC, NicholasKrupenin commented on app/helpers/application_helper.rb
> -  def flash_message(type)
+

2023-04-26 09:36 UTC, NicholasKrupenin commented on app/views/devise/sessions/new.html.erb
> +<h2>Log in</h2>
+

2023-04-26 11:57 UTC, NicholasKrupenin commented on db/migrate/20230423222234_add_attribute_name_to_users.rb
> +  def change
+

2023-04-27 05:11 UTC, VidgarVii requested changes

2023-04-27 05:11 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id)
нет больше смысла принимать параметр author_id

2023-04-27 05:11 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    flash[:notice] = "Welcome #{current_user.first_name}! You are logged in as #{current_user.type}!"
этот метод должен просто возвращать путь
то что он еще и флеш устанавливает - неожиданный сайд эффект
к примеру, есть задача:
в админке выводить список пользователей с урлами, куда каждый будет редиректнут после логина
метод называется `after_sign_in_path_for(user)` - вполне логично им воспользоваться
и вдруг неожиданность - у админа почему-то выводится флеш-привествие )))
ТЗ: "... после входа, выводить флэш-сообщение ..."
обрати внимание - "после входа", т.е. установку флеша надо делать там, где происходит логин пользователя (создание сессии), т.е. в `SessionsController`

2023-04-27 05:11 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-04-27 11:09 UTC, NicholasKrupenin commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id)
+

2023-04-27 11:10 UTC, NicholasKrupenin commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
+

2023-04-27 12:36 UTC, NicholasKrupenin commented on app/controllers/application_controller.rb
> +    flash[:notice] = "Welcome #{current_user.first_name}! You are logged in as #{current_user.type}!"
+

2023-04-27 13:27 UTC, merged