Lesson 13
NicholasKrupenin/TestGuru pull request #16
Opened 2023-05-11 03:39 UTC by NicholasKrupenin

Привет 0/

2023-05-11 05:18 UTC, VidgarVii requested changes

2023-05-11 05:18 UTC, VidgarVii commented on '
> +ru:
мне кажется этот файл потерялся и имеет не верное название

2023-05-11 05:18 UTC, VidgarVii commented on app/assets/javascripts/applications.js
> +// This is a manifest file that'll be compiled into application.js, which will include all the files
уже есть папка с JS
app/javascript/

2023-05-11 05:18 UTC, VidgarVii commented on .gitignore
> +.env
секреты скрыты, это хорошо. Но другому разработчику надо понять какие ЕНВ нужны для проекта.
По этому надо добавить файл .env.example, который будет содержать пустые ЕНВ 

Хорошей практикой будет в репозиторий положить .env.example Который будет хранить пустые переменные окружения

2023-05-11 05:18 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +  before_action :test_passages, only: :create
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-05-11 05:18 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    new_gist.call
`new_gist = GistQuestionService.new(@test_passage.current_question).call`

2023-05-11 05:18 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      Gist.create(question: @test_passage.current_question, user: current_user,
так как тут не проверяем входящие параметры при создания объекта то лучше воспользоваться bang! методом. Чтобы точно знать что код работает и Gist в базе создаётся

2023-05-11 05:18 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if new_gist.successful?
для проверки рзультата работы сервисов принято называть метод `success?`

2023-05-11 05:18 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def successful?
Сейчас если после new вызывать например successful? или show_url то будет ошибка. А вот конструкция объекта об этом не говорит. Что методы надо вызывать в какой-то последовательностью. Вот этой последовательности не должно быть. 
Чтобы исправить. Надо сделать так чтобы метод call возвращал такой объект, который будет содержать все нужные методы и данные. С которым будет работать констроллер.
Самый просто вариант использовать структуру
https://ruby-doc.org/core-2.5.0/Struct.html

2023-05-11 05:18 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
если токена не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Лучше проверку токена делать явной. Для этого можно воспользоваться  fetch
ENV.fetch('GITHUB_TOKEN')

2023-05-11 05:18 UTC, VidgarVii commented on config/locales/en/en.yml
> +    success: "Gist created: %{url}"
урл должен быть кликабелен для юзера

2023-05-12 04:39 UTC, VidgarVii commented on config/application.rb
>      config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
это настройка вообще не нужна

2023-05-12 04:39 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :en
лучше оставить русскую локаль, чтобы понять что локализовано, а что нет

2023-05-12 04:39 UTC, VidgarVii commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
сейчас ни чего нет в этих папках

2023-05-12 04:39 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      flash[:notice] = "#{t('.success')} #{view_context.link_to result.show_url, result.show_url}"
http://rusrails.ru/i18n#ispolzovanie-html-bezopasnyh-perevodov

2023-05-15 22:02 UTC, NicholasKrupenin commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
+

2023-05-15 22:02 UTC, NicholasKrupenin commented on config/application.rb
> +    config.i18n.default_locale = :en
+

2023-05-15 22:02 UTC, NicholasKrupenin commented on config/application.rb
>      config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
-

2023-05-15 22:02 UTC, NicholasKrupenin commented on config/application.rb
>      config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
!

2023-05-17 12:31 UTC, merged