Lesson 2
NicholasKrupenin/TestGuru pull request #5
Opened 2022-08-22 11:35 UTC by NicholasKrupenin

Добрый день.

2022-08-22 16:28 UTC, VidgarVii requested changes

2022-08-22 16:28 UTC, VidgarVii commented on Gemfile
> +gem 'irb'
это точно лишние гемы) У рельсы своя консоль

2022-08-22 16:28 UTC, VidgarVii commented on db/migrate/20220822112314_create_tests.rb
> +      t.timestamps
для теста нам еще понадобиться автор. Это юзер который создал тест. Давай сделаем это в текущем ПР
t.references :author ....

2022-08-23 15:54 UTC, NicholasKrupenin commented on Gemfile
> +gem 'irb'
irb через рельсы не работали (немного погуглив узнал что виноват Arch)
[Rails console](https://github.com/rails/rails/issues/42373)

2022-08-23 15:55 UTC, NicholasKrupenin commented on db/migrate/20220822112314_create_tests.rb
> +      t.timestamps
Добавил author

2022-08-24 01:51 UTC, VidgarVii requested changes

2022-08-24 01:51 UTC, VidgarVii commented on db/migrate/20220822112314_create_tests.rb
> +      t.references :author, null: false, foreign_key: true
Не нужно создавать отдельную таблицу авторов. Автор это тот же юзер.
Надо сделать так чтобы внешний ключ ссылался на таблицу юзеры, а не авторы. Но при этом название колонки должно сохраниться. Для этого есть опция to_table

2022-08-24 03:58 UTC, NicholasKrupenin commented on db/migrate/20220822112314_create_tests.rb
> +      t.references :author, null: false, foreign_key: true
Дополнил

2022-09-14 07:51 UTC, merged