Lesson 4
NicholasKrupenin/TestGuru pull request #7
Opened 2022-12-18 10:17 UTC by NicholasKrupenin

0/

2022-12-19 05:00 UTC, VidgarVii requested changes

2022-12-19 05:00 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-12-19 05:00 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-12-19 05:00 UTC, VidgarVii commented on app/models/test.rb
>      joins('JOIN categories ON tests.category_id = categories.id')
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-12-19 05:00 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('JOIN test_users ON test_users.test_id = tests.id')
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2022-12-19 05:00 UTC, VidgarVii commented on app/models/test.rb
> +
По ассоциациям получается что тест принадлежит юзеру и так же имеет много юзеров.
Звучит как то странно и не понятно

2022-12-19 05:00 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('JOIN test_users ON test_users.test_id = tests.id')
так же в сидах теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-12-27 21:56 UTC, NicholasKrupenin commented on app/models/question.rb
> +  has_many :answers
Исправил

2022-12-27 21:56 UTC, NicholasKrupenin commented on app/models/category.rb
> +  has_many :tests
Добавил `dependent: ...`

2022-12-27 21:56 UTC, NicholasKrupenin commented on app/models/test.rb
>      joins('JOIN categories ON tests.category_id = categories.id')
Исправил

2022-12-27 21:58 UTC, NicholasKrupenin commented on app/models/test.rb
> +
Исправил

2022-12-27 22:08 UTC, NicholasKrupenin commented on app/models/user.rb
>      Test.joins('JOIN test_users ON test_users.test_id = tests.id')
дополнил

2023-01-10 12:19 UTC, merged