rest_rails_controller
NicholasKrupenin/TestGuru pull request #9
Opened 2023-03-21 21:32 UTC by NicholasKrupenin

Привет 0/

2023-03-22 06:37 UTC, VidgarVii requested changes

2023-03-22 06:37 UTC, VidgarVii commented on config/routes.rb
> +  #delete "/questions/:id", to: "questions#destroy", as: "destroy_question"
не используемый код стоит уадялть, а не комментировать

2023-03-22 06:37 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<%= form_with url: test_questions_url, method: :post do |form| %>
урл хелпер использован не корректно. Для какого теста будет создан вопрос? И вопрос ли вообще по названию метода без аргументов не понятно. 
Лучше явно передавать объекты model: [@test, @question]. И хелпер form_with сам построит нужный action

форма сейчас создана не верно. Тут нет явного указания что будет создан вопрос. Нет вложенности полей в ресурс.  Пересмотри скринкаст.

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
в методе лишние отступы и не нужный коммент

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if @question.save
тут происходит двойная попытка сохранения вопроса в базу.
Достаточно 1 раз породить объект и попытаться его записать

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path
лучше всегда писать путь согласно конвенции, т.е. с явной передачей аргумента в хелпер:
```ruby
test_questions_path(@test)
```
а вообще после создания/обновления ресурса, принято юзеру показывать этот самый ресуср

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
`test_id` не нужно в разрешенных параметрах в явном виде указывать
также посмотри в форму - там тоже нет ничего похожего на `<input type="text" name="question[test_id]" id="question-test_id">`

в скринкасте:
кроме метода `permit` используется еще метод `require` (он необходим, чтобы обратиться не просто к параметрам, а к определенному ключу)`

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index new]
тест еще нужен для экшена create

2023-03-22 06:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
нет экшена show

2023-03-22 13:14 UTC, NicholasKrupenin commented on config/routes.rb
> +  #delete "/questions/:id", to: "questions#destroy", as: "destroy_question"
ok

2023-03-22 13:14 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +  end
ok

2023-03-22 13:19 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +    if @question.save
ok

2023-03-22 13:20 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index new]
ok

2023-03-22 20:10 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +  end
ok

2023-03-22 20:10 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +
ok

2023-03-23 05:15 UTC, VidgarVii requested changes

2023-03-23 05:15 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация на русском

2023-03-23 05:15 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :en
лучше остаться на русском. Потом будет делать локализацию. Если есть баги, то их надо починить, а не избегать

2023-03-23 05:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def show; end
экшен ни чего не отдаёт. Страница не работает

2023-03-23 05:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path(@test)
https://github.com/NicholasKrupenin/TestGuru/pull/9#discussion_r1144288130

2023-03-23 05:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: 'Question was deleted!'
лучше сделать редирект на другую страницу, чтобы у юзера была возможность продолжить работу на сайте.

2023-03-23 15:18 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +    render plain: 'Question was deleted!'
Сделал редирект на список вопросов теста

2023-03-23 15:18 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path(@test)
Сделал на show

2023-03-23 15:18 UTC, NicholasKrupenin commented on app/controllers/questions_controller.rb
> +  def show; end
ok

2023-03-24 20:24 UTC, merged